/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CardUidRouteImport } from './routes/card.$uid'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUnverifiedRouteImport } from './routes/admin/unverified'
import { Route as AdminReverifyRouteImport } from './routes/admin/reverify'
import { Route as AdminRechargesRouteImport } from './routes/admin/recharges'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AdminFacesRouteImport } from './routes/admin/faces'
import { Route as AdminBonusSettingsRouteImport } from './routes/admin/bonus-settings'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedReverifyRouteImport } from './routes/_authenticated/reverify'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedRechargeRouteImport } from './routes/_authenticated/recharge'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as ApiPublicWhitelistRecheckRouteImport } from './routes/api/public/whitelist-recheck'
import { Route as ApiPublicTourAudioRouteImport } from './routes/api/public/tour-audio'
import { Route as AdminUserUserIdRouteImport } from './routes/admin/user.$userId'
import { Route as AuthenticatedTaskSlotRouteImport } from './routes/_authenticated/task.$slot'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CardUidRoute = CardUidRouteImport.update({
  id: '/card/$uid',
  path: '/card/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnverifiedRoute = AdminUnverifiedRouteImport.update({
  id: '/unverified',
  path: '/unverified',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReverifyRoute = AdminReverifyRouteImport.update({
  id: '/reverify',
  path: '/reverify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRechargesRoute = AdminRechargesRouteImport.update({
  id: '/recharges',
  path: '/recharges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacesRoute = AdminFacesRouteImport.update({
  id: '/faces',
  path: '/faces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBonusSettingsRoute = AdminBonusSettingsRouteImport.update({
  id: '/bonus-settings',
  path: '/bonus-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReverifyRoute = AuthenticatedReverifyRouteImport.update({
  id: '/reverify',
  path: '/reverify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeRoute = AuthenticatedRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWhitelistRecheckRoute =
  ApiPublicWhitelistRecheckRouteImport.update({
    id: '/api/public/whitelist-recheck',
    path: '/api/public/whitelist-recheck',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTourAudioRoute = ApiPublicTourAudioRouteImport.update({
  id: '/api/public/tour-audio',
  path: '/api/public/tour-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserUserIdRoute = AdminUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTaskSlotRoute = AuthenticatedTaskSlotRouteImport.update({
  id: '/task/$slot',
  path: '/task/$slot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/reverify': typeof AuthenticatedReverifyRoute
  '/send': typeof AuthenticatedSendRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bonus-settings': typeof AdminBonusSettingsRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/card/$uid': typeof CardUidRoute
  '/admin/': typeof AdminIndexRoute
  '/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/tour-audio': typeof ApiPublicTourAudioRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/reverify': typeof AuthenticatedReverifyRoute
  '/send': typeof AuthenticatedSendRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bonus-settings': typeof AdminBonusSettingsRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/card/$uid': typeof CardUidRoute
  '/admin': typeof AdminIndexRoute
  '/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/tour-audio': typeof ApiPublicTourAudioRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recharge': typeof AuthenticatedRechargeRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/reverify': typeof AuthenticatedReverifyRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bonus-settings': typeof AdminBonusSettingsRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/card/$uid': typeof CardUidRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/tour-audio': typeof ApiPublicTourAudioRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/home'
    | '/kyc'
    | '/offers'
    | '/profile'
    | '/recharge'
    | '/referral'
    | '/reverify'
    | '/send'
    | '/wallet'
    | '/withdraw'
    | '/admin/announcements'
    | '/admin/bonus-settings'
    | '/admin/faces'
    | '/admin/kyc'
    | '/admin/recharges'
    | '/admin/reverify'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/card/$uid'
    | '/admin/'
    | '/task/$slot'
    | '/admin/user/$userId'
    | '/api/public/tour-audio'
    | '/api/public/whitelist-recheck'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/home'
    | '/kyc'
    | '/offers'
    | '/profile'
    | '/recharge'
    | '/referral'
    | '/reverify'
    | '/send'
    | '/wallet'
    | '/withdraw'
    | '/admin/announcements'
    | '/admin/bonus-settings'
    | '/admin/faces'
    | '/admin/kyc'
    | '/admin/recharges'
    | '/admin/reverify'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/card/$uid'
    | '/admin'
    | '/task/$slot'
    | '/admin/user/$userId'
    | '/api/public/tour-audio'
    | '/api/public/whitelist-recheck'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/kyc'
    | '/_authenticated/offers'
    | '/_authenticated/profile'
    | '/_authenticated/recharge'
    | '/_authenticated/referral'
    | '/_authenticated/reverify'
    | '/_authenticated/send'
    | '/_authenticated/wallet'
    | '/_authenticated/withdraw'
    | '/admin/announcements'
    | '/admin/bonus-settings'
    | '/admin/faces'
    | '/admin/kyc'
    | '/admin/recharges'
    | '/admin/reverify'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/card/$uid'
    | '/admin/'
    | '/_authenticated/task/$slot'
    | '/admin/user/$userId'
    | '/api/public/tour-audio'
    | '/api/public/whitelist-recheck'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  CardUidRoute: typeof CardUidRoute
  ApiPublicTourAudioRoute: typeof ApiPublicTourAudioRoute
  ApiPublicWhitelistRecheckRoute: typeof ApiPublicWhitelistRecheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/card/$uid': {
      id: '/card/$uid'
      path: '/card/$uid'
      fullPath: '/card/$uid'
      preLoaderRoute: typeof CardUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unverified': {
      id: '/admin/unverified'
      path: '/unverified'
      fullPath: '/admin/unverified'
      preLoaderRoute: typeof AdminUnverifiedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reverify': {
      id: '/admin/reverify'
      path: '/reverify'
      fullPath: '/admin/reverify'
      preLoaderRoute: typeof AdminReverifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recharges': {
      id: '/admin/recharges'
      path: '/recharges'
      fullPath: '/admin/recharges'
      preLoaderRoute: typeof AdminRechargesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faces': {
      id: '/admin/faces'
      path: '/faces'
      fullPath: '/admin/faces'
      preLoaderRoute: typeof AdminFacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bonus-settings': {
      id: '/admin/bonus-settings'
      path: '/bonus-settings'
      fullPath: '/admin/bonus-settings'
      preLoaderRoute: typeof AdminBonusSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reverify': {
      id: '/_authenticated/reverify'
      path: '/reverify'
      fullPath: '/reverify'
      preLoaderRoute: typeof AuthenticatedReverifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge': {
      id: '/_authenticated/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof AuthenticatedRechargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whitelist-recheck': {
      id: '/api/public/whitelist-recheck'
      path: '/api/public/whitelist-recheck'
      fullPath: '/api/public/whitelist-recheck'
      preLoaderRoute: typeof ApiPublicWhitelistRecheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tour-audio': {
      id: '/api/public/tour-audio'
      path: '/api/public/tour-audio'
      fullPath: '/api/public/tour-audio'
      preLoaderRoute: typeof ApiPublicTourAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/$userId': {
      id: '/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AdminUserUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/task/$slot': {
      id: '/_authenticated/task/$slot'
      path: '/task/$slot'
      fullPath: '/task/$slot'
      preLoaderRoute: typeof AuthenticatedTaskSlotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRechargeRoute: typeof AuthenticatedRechargeRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedReverifyRoute: typeof AuthenticatedReverifyRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
  AuthenticatedTaskSlotRoute: typeof AuthenticatedTaskSlotRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRechargeRoute: AuthenticatedRechargeRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedReverifyRoute: AuthenticatedReverifyRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
  AuthenticatedTaskSlotRoute: AuthenticatedTaskSlotRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBonusSettingsRoute: typeof AdminBonusSettingsRoute
  AdminFacesRoute: typeof AdminFacesRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminRechargesRoute: typeof AdminRechargesRoute
  AdminReverifyRoute: typeof AdminReverifyRoute
  AdminUnverifiedRoute: typeof AdminUnverifiedRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUserUserIdRoute: typeof AdminUserUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBonusSettingsRoute: AdminBonusSettingsRoute,
  AdminFacesRoute: AdminFacesRoute,
  AdminKycRoute: AdminKycRoute,
  AdminRechargesRoute: AdminRechargesRoute,
  AdminReverifyRoute: AdminReverifyRoute,
  AdminUnverifiedRoute: AdminUnverifiedRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUserUserIdRoute: AdminUserUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  CardUidRoute: CardUidRoute,
  ApiPublicTourAudioRoute: ApiPublicTourAudioRoute,
  ApiPublicWhitelistRecheckRoute: ApiPublicWhitelistRecheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
