/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DataSafetyRouteImport } from './routes/data-safety'
import { Route as ChildSafetyRouteImport } from './routes/child-safety'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CardUidRouteImport } from './routes/card.$uid'
import { Route as AuthNativeCallbackRouteImport } from './routes/auth.native-callback'
import { Route as ApiYoutubeShortsRouteImport } from './routes/api/youtube-shorts'
import { Route as ApiYoutubeSearchRouteImport } from './routes/api/youtube-search'
import { Route as ApiTiktokFeedRouteImport } from './routes/api/tiktok-feed'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUnverifiedRouteImport } from './routes/admin/unverified'
import { Route as AdminTelegramRouteImport } from './routes/admin/telegram'
import { Route as AdminReverifyRouteImport } from './routes/admin/reverify'
import { Route as AdminRechargesRouteImport } from './routes/admin/recharges'
import { Route as AdminPaidReportRouteImport } from './routes/admin/paid-report'
import { Route as AdminMiningRouteImport } from './routes/admin/mining'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AdminFacesRouteImport } from './routes/admin/faces'
import { Route as AdminCountriesRouteImport } from './routes/admin/countries'
import { Route as AdminCeloGasTransferRouteImport } from './routes/admin/celo-gas-transfer'
import { Route as AdminCardsRouteImport } from './routes/admin/cards'
import { Route as AdminBonusSettingsRouteImport } from './routes/admin/bonus-settings'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedReverifyRouteImport } from './routes/_authenticated/reverify'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedRechargeRouteImport } from './routes/_authenticated/recharge'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedCoinsRouteImport } from './routes/_authenticated/coins'
import { Route as AuthenticatedSocialIndexRouteImport } from './routes/_authenticated/social/index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as ApiPublicWhitelistRecheckRouteImport } from './routes/api/public/whitelist-recheck'
import { Route as ApiPublicTourAudioRouteImport } from './routes/api/public/tour-audio'
import { Route as ApiPublicReverifyRemindersRouteImport } from './routes/api/public/reverify-reminders'
import { Route as ApiPublicIpaybdWebhookRouteImport } from './routes/api/public/ipaybd-webhook'
import { Route as ApiPublicHisabCardRouteImport } from './routes/api/public/hisab-card'
import { Route as AdminUserUserIdRouteImport } from './routes/admin/user.$userId'
import { Route as AuthenticatedWatchPostIdRouteImport } from './routes/_authenticated/watch.$postId'
import { Route as AuthenticatedUserUserIdRouteImport } from './routes/_authenticated/user.$userId'
import { Route as AuthenticatedTaskSlotRouteImport } from './routes/_authenticated/task.$slot'
import { Route as AuthenticatedSocialMessengerRouteImport } from './routes/_authenticated/social/messenger'
import { Route as AuthenticatedChatPeerIdRouteImport } from './routes/_authenticated/chat.$peerId'
import { Route as AuthenticatedChannelUserIdRouteImport } from './routes/_authenticated/channel/$userId'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicPushNoticeRouteImport } from './routes/api/public/push/notice'
import { Route as ApiPublicPushFeedNotificationRouteImport } from './routes/api/public/push/feed-notification'
import { Route as ApiPublicPayoutBridgeRouteImport } from './routes/api/public/payout/bridge'
import { Route as ApiPublicOnchainScanRunRouteImport } from './routes/api/public/onchain-scan/run'
import { Route as ApiPublicChatReplyRouteImport } from './routes/api/public/chat/reply'
import { Route as ApiPublicCeloSweepRunRouteImport } from './routes/api/public/celo-sweep/run'
import { Route as ApiPublicBroadcastRunRouteImport } from './routes/api/public/broadcast/run'
import { Route as ApiPublicAutoEngageRunRouteImport } from './routes/api/public/auto-engage/run'
import { Route as ApiPublicAppDownloadRouteImport } from './routes/api/public/app/download'
import { Route as AuthenticatedChatGroupGroupIdRouteImport } from './routes/_authenticated/chat.group.$groupId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSafetyRoute = DataSafetyRouteImport.update({
  id: '/data-safety',
  path: '/data-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildSafetyRoute = ChildSafetyRouteImport.update({
  id: '/child-safety',
  path: '/child-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CardUidRoute = CardUidRouteImport.update({
  id: '/card/$uid',
  path: '/card/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNativeCallbackRoute = AuthNativeCallbackRouteImport.update({
  id: '/native-callback',
  path: '/native-callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiYoutubeShortsRoute = ApiYoutubeShortsRouteImport.update({
  id: '/api/youtube-shorts',
  path: '/api/youtube-shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeSearchRoute = ApiYoutubeSearchRouteImport.update({
  id: '/api/youtube-search',
  path: '/api/youtube-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTiktokFeedRoute = ApiTiktokFeedRouteImport.update({
  id: '/api/tiktok-feed',
  path: '/api/tiktok-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnverifiedRoute = AdminUnverifiedRouteImport.update({
  id: '/unverified',
  path: '/unverified',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReverifyRoute = AdminReverifyRouteImport.update({
  id: '/reverify',
  path: '/reverify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRechargesRoute = AdminRechargesRouteImport.update({
  id: '/recharges',
  path: '/recharges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaidReportRoute = AdminPaidReportRouteImport.update({
  id: '/paid-report',
  path: '/paid-report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMiningRoute = AdminMiningRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacesRoute = AdminFacesRouteImport.update({
  id: '/faces',
  path: '/faces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCountriesRoute = AdminCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCeloGasTransferRoute = AdminCeloGasTransferRouteImport.update({
  id: '/celo-gas-transfer',
  path: '/celo-gas-transfer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBonusSettingsRoute = AdminBonusSettingsRouteImport.update({
  id: '/bonus-settings',
  path: '/bonus-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReverifyRoute = AuthenticatedReverifyRouteImport.update({
  id: '/reverify',
  path: '/reverify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeRoute = AuthenticatedRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoinsRoute = AuthenticatedCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialIndexRoute =
  AuthenticatedSocialIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSocialRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhitelistRecheckRoute =
  ApiPublicWhitelistRecheckRouteImport.update({
    id: '/api/public/whitelist-recheck',
    path: '/api/public/whitelist-recheck',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTourAudioRoute = ApiPublicTourAudioRouteImport.update({
  id: '/api/public/tour-audio',
  path: '/api/public/tour-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReverifyRemindersRoute =
  ApiPublicReverifyRemindersRouteImport.update({
    id: '/api/public/reverify-reminders',
    path: '/api/public/reverify-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIpaybdWebhookRoute = ApiPublicIpaybdWebhookRouteImport.update({
  id: '/api/public/ipaybd-webhook',
  path: '/api/public/ipaybd-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHisabCardRoute = ApiPublicHisabCardRouteImport.update({
  id: '/api/public/hisab-card',
  path: '/api/public/hisab-card',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserUserIdRoute = AdminUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWatchPostIdRoute =
  AuthenticatedWatchPostIdRouteImport.update({
    id: '/watch/$postId',
    path: '/watch/$postId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserUserIdRoute = AuthenticatedUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskSlotRoute = AuthenticatedTaskSlotRouteImport.update({
  id: '/task/$slot',
  path: '/task/$slot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialMessengerRoute =
  AuthenticatedSocialMessengerRouteImport.update({
    id: '/messenger',
    path: '/messenger',
    getParentRoute: () => AuthenticatedSocialRoute,
  } as any)
const AuthenticatedChatPeerIdRoute = AuthenticatedChatPeerIdRouteImport.update({
  id: '/chat/$peerId',
  path: '/chat/$peerId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelUserIdRoute =
  AuthenticatedChannelUserIdRouteImport.update({
    id: '/channel/$userId',
    path: '/channel/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushNoticeRoute = ApiPublicPushNoticeRouteImport.update({
  id: '/api/public/push/notice',
  path: '/api/public/push/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushFeedNotificationRoute =
  ApiPublicPushFeedNotificationRouteImport.update({
    id: '/api/public/push/feed-notification',
    path: '/api/public/push/feed-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPayoutBridgeRoute = ApiPublicPayoutBridgeRouteImport.update({
  id: '/api/public/payout/bridge',
  path: '/api/public/payout/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOnchainScanRunRoute = ApiPublicOnchainScanRunRouteImport.update({
  id: '/api/public/onchain-scan/run',
  path: '/api/public/onchain-scan/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatReplyRoute = ApiPublicChatReplyRouteImport.update({
  id: '/api/public/chat/reply',
  path: '/api/public/chat/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCeloSweepRunRoute = ApiPublicCeloSweepRunRouteImport.update({
  id: '/api/public/celo-sweep/run',
  path: '/api/public/celo-sweep/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBroadcastRunRoute = ApiPublicBroadcastRunRouteImport.update({
  id: '/api/public/broadcast/run',
  path: '/api/public/broadcast/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutoEngageRunRoute = ApiPublicAutoEngageRunRouteImport.update({
  id: '/api/public/auto-engage/run',
  path: '/api/public/auto-engage/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppDownloadRoute = ApiPublicAppDownloadRouteImport.update({
  id: '/api/public/app/download',
  path: '/api/public/app/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatGroupGroupIdRoute =
  AuthenticatedChatGroupGroupIdRouteImport.update({
    id: '/chat/group/$groupId',
    path: '/chat/group/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRouteWithChildren
  '/child-safety': typeof ChildSafetyRoute
  '/data-safety': typeof DataSafetyRoute
  '/download': typeof DownloadRoute
  '/earn': typeof EarnRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/rules': typeof RulesRoute
  '/terms': typeof TermsRoute
  '/coins': typeof AuthenticatedCoinsRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/reverify': typeof AuthenticatedReverifyRoute
  '/send': typeof AuthenticatedSendRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/social': typeof AuthenticatedSocialRouteWithChildren
  '/studio': typeof AuthenticatedStudioRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bonus-settings': typeof AdminBonusSettingsRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/celo-gas-transfer': typeof AdminCeloGasTransferRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/mining': typeof AdminMiningRoute
  '/admin/paid-report': typeof AdminPaidReportRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/api/tiktok-feed': typeof ApiTiktokFeedRoute
  '/api/youtube-search': typeof ApiYoutubeSearchRoute
  '/api/youtube-shorts': typeof ApiYoutubeShortsRoute
  '/auth/native-callback': typeof AuthNativeCallbackRoute
  '/card/$uid': typeof CardUidRoute
  '/admin/': typeof AdminIndexRoute
  '/channel/$userId': typeof AuthenticatedChannelUserIdRoute
  '/chat/$peerId': typeof AuthenticatedChatPeerIdRoute
  '/social/messenger': typeof AuthenticatedSocialMessengerRoute
  '/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/user/$userId': typeof AuthenticatedUserUserIdRoute
  '/watch/$postId': typeof AuthenticatedWatchPostIdRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/hisab-card': typeof ApiPublicHisabCardRoute
  '/api/public/ipaybd-webhook': typeof ApiPublicIpaybdWebhookRoute
  '/api/public/reverify-reminders': typeof ApiPublicReverifyRemindersRoute
  '/api/public/tour-audio': typeof ApiPublicTourAudioRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/social/': typeof AuthenticatedSocialIndexRoute
  '/chat/group/$groupId': typeof AuthenticatedChatGroupGroupIdRoute
  '/api/public/app/download': typeof ApiPublicAppDownloadRoute
  '/api/public/auto-engage/run': typeof ApiPublicAutoEngageRunRoute
  '/api/public/broadcast/run': typeof ApiPublicBroadcastRunRoute
  '/api/public/celo-sweep/run': typeof ApiPublicCeloSweepRunRoute
  '/api/public/chat/reply': typeof ApiPublicChatReplyRoute
  '/api/public/onchain-scan/run': typeof ApiPublicOnchainScanRunRoute
  '/api/public/payout/bridge': typeof ApiPublicPayoutBridgeRoute
  '/api/public/push/feed-notification': typeof ApiPublicPushFeedNotificationRoute
  '/api/public/push/notice': typeof ApiPublicPushNoticeRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRouteWithChildren
  '/child-safety': typeof ChildSafetyRoute
  '/data-safety': typeof DataSafetyRoute
  '/download': typeof DownloadRoute
  '/earn': typeof EarnRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/rules': typeof RulesRoute
  '/terms': typeof TermsRoute
  '/coins': typeof AuthenticatedCoinsRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/reverify': typeof AuthenticatedReverifyRoute
  '/send': typeof AuthenticatedSendRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bonus-settings': typeof AdminBonusSettingsRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/celo-gas-transfer': typeof AdminCeloGasTransferRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/mining': typeof AdminMiningRoute
  '/admin/paid-report': typeof AdminPaidReportRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/api/tiktok-feed': typeof ApiTiktokFeedRoute
  '/api/youtube-search': typeof ApiYoutubeSearchRoute
  '/api/youtube-shorts': typeof ApiYoutubeShortsRoute
  '/auth/native-callback': typeof AuthNativeCallbackRoute
  '/card/$uid': typeof CardUidRoute
  '/admin': typeof AdminIndexRoute
  '/channel/$userId': typeof AuthenticatedChannelUserIdRoute
  '/chat/$peerId': typeof AuthenticatedChatPeerIdRoute
  '/social/messenger': typeof AuthenticatedSocialMessengerRoute
  '/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/user/$userId': typeof AuthenticatedUserUserIdRoute
  '/watch/$postId': typeof AuthenticatedWatchPostIdRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/hisab-card': typeof ApiPublicHisabCardRoute
  '/api/public/ipaybd-webhook': typeof ApiPublicIpaybdWebhookRoute
  '/api/public/reverify-reminders': typeof ApiPublicReverifyRemindersRoute
  '/api/public/tour-audio': typeof ApiPublicTourAudioRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/social': typeof AuthenticatedSocialIndexRoute
  '/chat/group/$groupId': typeof AuthenticatedChatGroupGroupIdRoute
  '/api/public/app/download': typeof ApiPublicAppDownloadRoute
  '/api/public/auto-engage/run': typeof ApiPublicAutoEngageRunRoute
  '/api/public/broadcast/run': typeof ApiPublicBroadcastRunRoute
  '/api/public/celo-sweep/run': typeof ApiPublicCeloSweepRunRoute
  '/api/public/chat/reply': typeof ApiPublicChatReplyRoute
  '/api/public/onchain-scan/run': typeof ApiPublicOnchainScanRunRoute
  '/api/public/payout/bridge': typeof ApiPublicPayoutBridgeRoute
  '/api/public/push/feed-notification': typeof ApiPublicPushFeedNotificationRoute
  '/api/public/push/notice': typeof ApiPublicPushNoticeRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account-deletion': typeof AccountDeletionRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRouteWithChildren
  '/child-safety': typeof ChildSafetyRoute
  '/data-safety': typeof DataSafetyRoute
  '/download': typeof DownloadRoute
  '/earn': typeof EarnRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/rules': typeof RulesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/coins': typeof AuthenticatedCoinsRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recharge': typeof AuthenticatedRechargeRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/reverify': typeof AuthenticatedReverifyRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/social': typeof AuthenticatedSocialRouteWithChildren
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bonus-settings': typeof AdminBonusSettingsRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/celo-gas-transfer': typeof AdminCeloGasTransferRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/mining': typeof AdminMiningRoute
  '/admin/paid-report': typeof AdminPaidReportRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/api/tiktok-feed': typeof ApiTiktokFeedRoute
  '/api/youtube-search': typeof ApiYoutubeSearchRoute
  '/api/youtube-shorts': typeof ApiYoutubeShortsRoute
  '/auth/native-callback': typeof AuthNativeCallbackRoute
  '/card/$uid': typeof CardUidRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/channel/$userId': typeof AuthenticatedChannelUserIdRoute
  '/_authenticated/chat/$peerId': typeof AuthenticatedChatPeerIdRoute
  '/_authenticated/social/messenger': typeof AuthenticatedSocialMessengerRoute
  '/_authenticated/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/_authenticated/user/$userId': typeof AuthenticatedUserUserIdRoute
  '/_authenticated/watch/$postId': typeof AuthenticatedWatchPostIdRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/hisab-card': typeof ApiPublicHisabCardRoute
  '/api/public/ipaybd-webhook': typeof ApiPublicIpaybdWebhookRoute
  '/api/public/reverify-reminders': typeof ApiPublicReverifyRemindersRoute
  '/api/public/tour-audio': typeof ApiPublicTourAudioRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/social/': typeof AuthenticatedSocialIndexRoute
  '/_authenticated/chat/group/$groupId': typeof AuthenticatedChatGroupGroupIdRoute
  '/api/public/app/download': typeof ApiPublicAppDownloadRoute
  '/api/public/auto-engage/run': typeof ApiPublicAutoEngageRunRoute
  '/api/public/broadcast/run': typeof ApiPublicBroadcastRunRoute
  '/api/public/celo-sweep/run': typeof ApiPublicCeloSweepRunRoute
  '/api/public/chat/reply': typeof ApiPublicChatReplyRoute
  '/api/public/onchain-scan/run': typeof ApiPublicOnchainScanRunRoute
  '/api/public/payout/bridge': typeof ApiPublicPayoutBridgeRoute
  '/api/public/push/feed-notification': typeof ApiPublicPushFeedNotificationRoute
  '/api/public/push/notice': typeof ApiPublicPushNoticeRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deletion'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/child-safety'
    | '/data-safety'
    | '/download'
    | '/earn'
    | '/privacy'
    | '/rates'
    | '/rules'
    | '/terms'
    | '/coins'
    | '/earnings'
    | '/feed'
    | '/friends'
    | '/history'
    | '/home'
    | '/kyc'
    | '/menu'
    | '/offers'
    | '/profile'
    | '/recharge'
    | '/reels'
    | '/referral'
    | '/reverify'
    | '/send'
    | '/settings'
    | '/shop'
    | '/social'
    | '/studio'
    | '/videos'
    | '/wallet'
    | '/withdraw'
    | '/admin/announcements'
    | '/admin/bonus-settings'
    | '/admin/cards'
    | '/admin/celo-gas-transfer'
    | '/admin/countries'
    | '/admin/faces'
    | '/admin/kyc'
    | '/admin/mining'
    | '/admin/paid-report'
    | '/admin/recharges'
    | '/admin/reverify'
    | '/admin/telegram'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/api/tiktok-feed'
    | '/api/youtube-search'
    | '/api/youtube-shorts'
    | '/auth/native-callback'
    | '/card/$uid'
    | '/admin/'
    | '/channel/$userId'
    | '/chat/$peerId'
    | '/social/messenger'
    | '/task/$slot'
    | '/user/$userId'
    | '/watch/$postId'
    | '/admin/user/$userId'
    | '/api/public/hisab-card'
    | '/api/public/ipaybd-webhook'
    | '/api/public/reverify-reminders'
    | '/api/public/tour-audio'
    | '/api/public/whitelist-recheck'
    | '/lovable/email/events'
    | '/chat/'
    | '/social/'
    | '/chat/group/$groupId'
    | '/api/public/app/download'
    | '/api/public/auto-engage/run'
    | '/api/public/broadcast/run'
    | '/api/public/celo-sweep/run'
    | '/api/public/chat/reply'
    | '/api/public/onchain-scan/run'
    | '/api/public/payout/bridge'
    | '/api/public/push/feed-notification'
    | '/api/public/push/notice'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/admin-login'
    | '/auth'
    | '/child-safety'
    | '/data-safety'
    | '/download'
    | '/earn'
    | '/privacy'
    | '/rates'
    | '/rules'
    | '/terms'
    | '/coins'
    | '/earnings'
    | '/feed'
    | '/friends'
    | '/history'
    | '/home'
    | '/kyc'
    | '/menu'
    | '/offers'
    | '/profile'
    | '/recharge'
    | '/reels'
    | '/referral'
    | '/reverify'
    | '/send'
    | '/settings'
    | '/shop'
    | '/studio'
    | '/videos'
    | '/wallet'
    | '/withdraw'
    | '/admin/announcements'
    | '/admin/bonus-settings'
    | '/admin/cards'
    | '/admin/celo-gas-transfer'
    | '/admin/countries'
    | '/admin/faces'
    | '/admin/kyc'
    | '/admin/mining'
    | '/admin/paid-report'
    | '/admin/recharges'
    | '/admin/reverify'
    | '/admin/telegram'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/api/tiktok-feed'
    | '/api/youtube-search'
    | '/api/youtube-shorts'
    | '/auth/native-callback'
    | '/card/$uid'
    | '/admin'
    | '/channel/$userId'
    | '/chat/$peerId'
    | '/social/messenger'
    | '/task/$slot'
    | '/user/$userId'
    | '/watch/$postId'
    | '/admin/user/$userId'
    | '/api/public/hisab-card'
    | '/api/public/ipaybd-webhook'
    | '/api/public/reverify-reminders'
    | '/api/public/tour-audio'
    | '/api/public/whitelist-recheck'
    | '/lovable/email/events'
    | '/chat'
    | '/social'
    | '/chat/group/$groupId'
    | '/api/public/app/download'
    | '/api/public/auto-engage/run'
    | '/api/public/broadcast/run'
    | '/api/public/celo-sweep/run'
    | '/api/public/chat/reply'
    | '/api/public/onchain-scan/run'
    | '/api/public/payout/bridge'
    | '/api/public/push/feed-notification'
    | '/api/public/push/notice'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account-deletion'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/child-safety'
    | '/data-safety'
    | '/download'
    | '/earn'
    | '/privacy'
    | '/rates'
    | '/rules'
    | '/terms'
    | '/_authenticated/coins'
    | '/_authenticated/earnings'
    | '/_authenticated/feed'
    | '/_authenticated/friends'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/kyc'
    | '/_authenticated/menu'
    | '/_authenticated/offers'
    | '/_authenticated/profile'
    | '/_authenticated/recharge'
    | '/_authenticated/reels'
    | '/_authenticated/referral'
    | '/_authenticated/reverify'
    | '/_authenticated/send'
    | '/_authenticated/settings'
    | '/_authenticated/shop'
    | '/_authenticated/social'
    | '/_authenticated/studio'
    | '/_authenticated/videos'
    | '/_authenticated/wallet'
    | '/_authenticated/withdraw'
    | '/admin/announcements'
    | '/admin/bonus-settings'
    | '/admin/cards'
    | '/admin/celo-gas-transfer'
    | '/admin/countries'
    | '/admin/faces'
    | '/admin/kyc'
    | '/admin/mining'
    | '/admin/paid-report'
    | '/admin/recharges'
    | '/admin/reverify'
    | '/admin/telegram'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/api/tiktok-feed'
    | '/api/youtube-search'
    | '/api/youtube-shorts'
    | '/auth/native-callback'
    | '/card/$uid'
    | '/admin/'
    | '/_authenticated/channel/$userId'
    | '/_authenticated/chat/$peerId'
    | '/_authenticated/social/messenger'
    | '/_authenticated/task/$slot'
    | '/_authenticated/user/$userId'
    | '/_authenticated/watch/$postId'
    | '/admin/user/$userId'
    | '/api/public/hisab-card'
    | '/api/public/ipaybd-webhook'
    | '/api/public/reverify-reminders'
    | '/api/public/tour-audio'
    | '/api/public/whitelist-recheck'
    | '/lovable/email/events'
    | '/_authenticated/chat/'
    | '/_authenticated/social/'
    | '/_authenticated/chat/group/$groupId'
    | '/api/public/app/download'
    | '/api/public/auto-engage/run'
    | '/api/public/broadcast/run'
    | '/api/public/celo-sweep/run'
    | '/api/public/chat/reply'
    | '/api/public/onchain-scan/run'
    | '/api/public/payout/bridge'
    | '/api/public/push/feed-notification'
    | '/api/public/push/notice'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountDeletionRoute: typeof AccountDeletionRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRouteWithChildren
  ChildSafetyRoute: typeof ChildSafetyRoute
  DataSafetyRoute: typeof DataSafetyRoute
  DownloadRoute: typeof DownloadRoute
  EarnRoute: typeof EarnRoute
  PrivacyRoute: typeof PrivacyRoute
  RatesRoute: typeof RatesRoute
  RulesRoute: typeof RulesRoute
  TermsRoute: typeof TermsRoute
  ApiTiktokFeedRoute: typeof ApiTiktokFeedRoute
  ApiYoutubeSearchRoute: typeof ApiYoutubeSearchRoute
  ApiYoutubeShortsRoute: typeof ApiYoutubeShortsRoute
  CardUidRoute: typeof CardUidRoute
  ApiPublicHisabCardRoute: typeof ApiPublicHisabCardRoute
  ApiPublicIpaybdWebhookRoute: typeof ApiPublicIpaybdWebhookRoute
  ApiPublicReverifyRemindersRoute: typeof ApiPublicReverifyRemindersRoute
  ApiPublicTourAudioRoute: typeof ApiPublicTourAudioRoute
  ApiPublicWhitelistRecheckRoute: typeof ApiPublicWhitelistRecheckRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicAppDownloadRoute: typeof ApiPublicAppDownloadRoute
  ApiPublicAutoEngageRunRoute: typeof ApiPublicAutoEngageRunRoute
  ApiPublicBroadcastRunRoute: typeof ApiPublicBroadcastRunRoute
  ApiPublicCeloSweepRunRoute: typeof ApiPublicCeloSweepRunRoute
  ApiPublicChatReplyRoute: typeof ApiPublicChatReplyRoute
  ApiPublicOnchainScanRunRoute: typeof ApiPublicOnchainScanRunRoute
  ApiPublicPayoutBridgeRoute: typeof ApiPublicPayoutBridgeRoute
  ApiPublicPushFeedNotificationRoute: typeof ApiPublicPushFeedNotificationRoute
  ApiPublicPushNoticeRoute: typeof ApiPublicPushNoticeRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-safety': {
      id: '/data-safety'
      path: '/data-safety'
      fullPath: '/data-safety'
      preLoaderRoute: typeof DataSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child-safety': {
      id: '/child-safety'
      path: '/child-safety'
      fullPath: '/child-safety'
      preLoaderRoute: typeof ChildSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/card/$uid': {
      id: '/card/$uid'
      path: '/card/$uid'
      fullPath: '/card/$uid'
      preLoaderRoute: typeof CardUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/native-callback': {
      id: '/auth/native-callback'
      path: '/native-callback'
      fullPath: '/auth/native-callback'
      preLoaderRoute: typeof AuthNativeCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/youtube-shorts': {
      id: '/api/youtube-shorts'
      path: '/api/youtube-shorts'
      fullPath: '/api/youtube-shorts'
      preLoaderRoute: typeof ApiYoutubeShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube-search': {
      id: '/api/youtube-search'
      path: '/api/youtube-search'
      fullPath: '/api/youtube-search'
      preLoaderRoute: typeof ApiYoutubeSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tiktok-feed': {
      id: '/api/tiktok-feed'
      path: '/api/tiktok-feed'
      fullPath: '/api/tiktok-feed'
      preLoaderRoute: typeof ApiTiktokFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unverified': {
      id: '/admin/unverified'
      path: '/unverified'
      fullPath: '/admin/unverified'
      preLoaderRoute: typeof AdminUnverifiedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reverify': {
      id: '/admin/reverify'
      path: '/reverify'
      fullPath: '/admin/reverify'
      preLoaderRoute: typeof AdminReverifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recharges': {
      id: '/admin/recharges'
      path: '/recharges'
      fullPath: '/admin/recharges'
      preLoaderRoute: typeof AdminRechargesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paid-report': {
      id: '/admin/paid-report'
      path: '/paid-report'
      fullPath: '/admin/paid-report'
      preLoaderRoute: typeof AdminPaidReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mining': {
      id: '/admin/mining'
      path: '/mining'
      fullPath: '/admin/mining'
      preLoaderRoute: typeof AdminMiningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faces': {
      id: '/admin/faces'
      path: '/faces'
      fullPath: '/admin/faces'
      preLoaderRoute: typeof AdminFacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/countries': {
      id: '/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AdminCountriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/celo-gas-transfer': {
      id: '/admin/celo-gas-transfer'
      path: '/celo-gas-transfer'
      fullPath: '/admin/celo-gas-transfer'
      preLoaderRoute: typeof AdminCeloGasTransferRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bonus-settings': {
      id: '/admin/bonus-settings'
      path: '/bonus-settings'
      fullPath: '/admin/bonus-settings'
      preLoaderRoute: typeof AdminBonusSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reverify': {
      id: '/_authenticated/reverify'
      path: '/reverify'
      fullPath: '/reverify'
      preLoaderRoute: typeof AuthenticatedReverifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge': {
      id: '/_authenticated/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof AuthenticatedRechargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coins': {
      id: '/_authenticated/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof AuthenticatedCoinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social/': {
      id: '/_authenticated/social/'
      path: '/'
      fullPath: '/social/'
      preLoaderRoute: typeof AuthenticatedSocialIndexRouteImport
      parentRoute: typeof AuthenticatedSocialRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whitelist-recheck': {
      id: '/api/public/whitelist-recheck'
      path: '/api/public/whitelist-recheck'
      fullPath: '/api/public/whitelist-recheck'
      preLoaderRoute: typeof ApiPublicWhitelistRecheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tour-audio': {
      id: '/api/public/tour-audio'
      path: '/api/public/tour-audio'
      fullPath: '/api/public/tour-audio'
      preLoaderRoute: typeof ApiPublicTourAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reverify-reminders': {
      id: '/api/public/reverify-reminders'
      path: '/api/public/reverify-reminders'
      fullPath: '/api/public/reverify-reminders'
      preLoaderRoute: typeof ApiPublicReverifyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ipaybd-webhook': {
      id: '/api/public/ipaybd-webhook'
      path: '/api/public/ipaybd-webhook'
      fullPath: '/api/public/ipaybd-webhook'
      preLoaderRoute: typeof ApiPublicIpaybdWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hisab-card': {
      id: '/api/public/hisab-card'
      path: '/api/public/hisab-card'
      fullPath: '/api/public/hisab-card'
      preLoaderRoute: typeof ApiPublicHisabCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/$userId': {
      id: '/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AdminUserUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/watch/$postId': {
      id: '/_authenticated/watch/$postId'
      path: '/watch/$postId'
      fullPath: '/watch/$postId'
      preLoaderRoute: typeof AuthenticatedWatchPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/$userId': {
      id: '/_authenticated/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof AuthenticatedUserUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task/$slot': {
      id: '/_authenticated/task/$slot'
      path: '/task/$slot'
      fullPath: '/task/$slot'
      preLoaderRoute: typeof AuthenticatedTaskSlotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social/messenger': {
      id: '/_authenticated/social/messenger'
      path: '/messenger'
      fullPath: '/social/messenger'
      preLoaderRoute: typeof AuthenticatedSocialMessengerRouteImport
      parentRoute: typeof AuthenticatedSocialRoute
    }
    '/_authenticated/chat/$peerId': {
      id: '/_authenticated/chat/$peerId'
      path: '/chat/$peerId'
      fullPath: '/chat/$peerId'
      preLoaderRoute: typeof AuthenticatedChatPeerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channel/$userId': {
      id: '/_authenticated/channel/$userId'
      path: '/channel/$userId'
      fullPath: '/channel/$userId'
      preLoaderRoute: typeof AuthenticatedChannelUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/notice': {
      id: '/api/public/push/notice'
      path: '/api/public/push/notice'
      fullPath: '/api/public/push/notice'
      preLoaderRoute: typeof ApiPublicPushNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/feed-notification': {
      id: '/api/public/push/feed-notification'
      path: '/api/public/push/feed-notification'
      fullPath: '/api/public/push/feed-notification'
      preLoaderRoute: typeof ApiPublicPushFeedNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payout/bridge': {
      id: '/api/public/payout/bridge'
      path: '/api/public/payout/bridge'
      fullPath: '/api/public/payout/bridge'
      preLoaderRoute: typeof ApiPublicPayoutBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/onchain-scan/run': {
      id: '/api/public/onchain-scan/run'
      path: '/api/public/onchain-scan/run'
      fullPath: '/api/public/onchain-scan/run'
      preLoaderRoute: typeof ApiPublicOnchainScanRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/reply': {
      id: '/api/public/chat/reply'
      path: '/api/public/chat/reply'
      fullPath: '/api/public/chat/reply'
      preLoaderRoute: typeof ApiPublicChatReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/celo-sweep/run': {
      id: '/api/public/celo-sweep/run'
      path: '/api/public/celo-sweep/run'
      fullPath: '/api/public/celo-sweep/run'
      preLoaderRoute: typeof ApiPublicCeloSweepRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/broadcast/run': {
      id: '/api/public/broadcast/run'
      path: '/api/public/broadcast/run'
      fullPath: '/api/public/broadcast/run'
      preLoaderRoute: typeof ApiPublicBroadcastRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auto-engage/run': {
      id: '/api/public/auto-engage/run'
      path: '/api/public/auto-engage/run'
      fullPath: '/api/public/auto-engage/run'
      preLoaderRoute: typeof ApiPublicAutoEngageRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app/download': {
      id: '/api/public/app/download'
      path: '/api/public/app/download'
      fullPath: '/api/public/app/download'
      preLoaderRoute: typeof ApiPublicAppDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/group/$groupId': {
      id: '/_authenticated/chat/group/$groupId'
      path: '/chat/group/$groupId'
      fullPath: '/chat/group/$groupId'
      preLoaderRoute: typeof AuthenticatedChatGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSocialRouteChildren {
  AuthenticatedSocialMessengerRoute: typeof AuthenticatedSocialMessengerRoute
  AuthenticatedSocialIndexRoute: typeof AuthenticatedSocialIndexRoute
}

const AuthenticatedSocialRouteChildren: AuthenticatedSocialRouteChildren = {
  AuthenticatedSocialMessengerRoute: AuthenticatedSocialMessengerRoute,
  AuthenticatedSocialIndexRoute: AuthenticatedSocialIndexRoute,
}

const AuthenticatedSocialRouteWithChildren =
  AuthenticatedSocialRoute._addFileChildren(AuthenticatedSocialRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoinsRoute: typeof AuthenticatedCoinsRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRechargeRoute: typeof AuthenticatedRechargeRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedReverifyRoute: typeof AuthenticatedReverifyRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRouteWithChildren
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
  AuthenticatedChannelUserIdRoute: typeof AuthenticatedChannelUserIdRoute
  AuthenticatedChatPeerIdRoute: typeof AuthenticatedChatPeerIdRoute
  AuthenticatedTaskSlotRoute: typeof AuthenticatedTaskSlotRoute
  AuthenticatedUserUserIdRoute: typeof AuthenticatedUserUserIdRoute
  AuthenticatedWatchPostIdRoute: typeof AuthenticatedWatchPostIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedChatGroupGroupIdRoute: typeof AuthenticatedChatGroupGroupIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoinsRoute: AuthenticatedCoinsRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRechargeRoute: AuthenticatedRechargeRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedReverifyRoute: AuthenticatedReverifyRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRouteWithChildren,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
  AuthenticatedChannelUserIdRoute: AuthenticatedChannelUserIdRoute,
  AuthenticatedChatPeerIdRoute: AuthenticatedChatPeerIdRoute,
  AuthenticatedTaskSlotRoute: AuthenticatedTaskSlotRoute,
  AuthenticatedUserUserIdRoute: AuthenticatedUserUserIdRoute,
  AuthenticatedWatchPostIdRoute: AuthenticatedWatchPostIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedChatGroupGroupIdRoute: AuthenticatedChatGroupGroupIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBonusSettingsRoute: typeof AdminBonusSettingsRoute
  AdminCardsRoute: typeof AdminCardsRoute
  AdminCeloGasTransferRoute: typeof AdminCeloGasTransferRoute
  AdminCountriesRoute: typeof AdminCountriesRoute
  AdminFacesRoute: typeof AdminFacesRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminMiningRoute: typeof AdminMiningRoute
  AdminPaidReportRoute: typeof AdminPaidReportRoute
  AdminRechargesRoute: typeof AdminRechargesRoute
  AdminReverifyRoute: typeof AdminReverifyRoute
  AdminTelegramRoute: typeof AdminTelegramRoute
  AdminUnverifiedRoute: typeof AdminUnverifiedRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUserUserIdRoute: typeof AdminUserUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBonusSettingsRoute: AdminBonusSettingsRoute,
  AdminCardsRoute: AdminCardsRoute,
  AdminCeloGasTransferRoute: AdminCeloGasTransferRoute,
  AdminCountriesRoute: AdminCountriesRoute,
  AdminFacesRoute: AdminFacesRoute,
  AdminKycRoute: AdminKycRoute,
  AdminMiningRoute: AdminMiningRoute,
  AdminPaidReportRoute: AdminPaidReportRoute,
  AdminRechargesRoute: AdminRechargesRoute,
  AdminReverifyRoute: AdminReverifyRoute,
  AdminTelegramRoute: AdminTelegramRoute,
  AdminUnverifiedRoute: AdminUnverifiedRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUserUserIdRoute: AdminUserUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthNativeCallbackRoute: typeof AuthNativeCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNativeCallbackRoute: AuthNativeCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountDeletionRoute: AccountDeletionRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRouteWithChildren,
  ChildSafetyRoute: ChildSafetyRoute,
  DataSafetyRoute: DataSafetyRoute,
  DownloadRoute: DownloadRoute,
  EarnRoute: EarnRoute,
  PrivacyRoute: PrivacyRoute,
  RatesRoute: RatesRoute,
  RulesRoute: RulesRoute,
  TermsRoute: TermsRoute,
  ApiTiktokFeedRoute: ApiTiktokFeedRoute,
  ApiYoutubeSearchRoute: ApiYoutubeSearchRoute,
  ApiYoutubeShortsRoute: ApiYoutubeShortsRoute,
  CardUidRoute: CardUidRoute,
  ApiPublicHisabCardRoute: ApiPublicHisabCardRoute,
  ApiPublicIpaybdWebhookRoute: ApiPublicIpaybdWebhookRoute,
  ApiPublicReverifyRemindersRoute: ApiPublicReverifyRemindersRoute,
  ApiPublicTourAudioRoute: ApiPublicTourAudioRoute,
  ApiPublicWhitelistRecheckRoute: ApiPublicWhitelistRecheckRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicAppDownloadRoute: ApiPublicAppDownloadRoute,
  ApiPublicAutoEngageRunRoute: ApiPublicAutoEngageRunRoute,
  ApiPublicBroadcastRunRoute: ApiPublicBroadcastRunRoute,
  ApiPublicCeloSweepRunRoute: ApiPublicCeloSweepRunRoute,
  ApiPublicChatReplyRoute: ApiPublicChatReplyRoute,
  ApiPublicOnchainScanRunRoute: ApiPublicOnchainScanRunRoute,
  ApiPublicPayoutBridgeRoute: ApiPublicPayoutBridgeRoute,
  ApiPublicPushFeedNotificationRoute: ApiPublicPushFeedNotificationRoute,
  ApiPublicPushNoticeRoute: ApiPublicPushNoticeRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
