/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CardUidRouteImport } from './routes/card.$uid'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUnverifiedRouteImport } from './routes/admin/unverified'
import { Route as AdminTelegramRouteImport } from './routes/admin/telegram'
import { Route as AdminReverifyRouteImport } from './routes/admin/reverify'
import { Route as AdminRechargesRouteImport } from './routes/admin/recharges'
import { Route as AdminPaidReportRouteImport } from './routes/admin/paid-report'
import { Route as AdminMiningRouteImport } from './routes/admin/mining'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AdminFacesRouteImport } from './routes/admin/faces'
import { Route as AdminBonusSettingsRouteImport } from './routes/admin/bonus-settings'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedReverifyRouteImport } from './routes/_authenticated/reverify'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedRechargeRouteImport } from './routes/_authenticated/recharge'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicWhitelistRecheckRouteImport } from './routes/api/public/whitelist-recheck'
import { Route as ApiPublicTourAudioRouteImport } from './routes/api/public/tour-audio'
import { Route as ApiPublicHisabCardRouteImport } from './routes/api/public/hisab-card'
import { Route as AdminUserUserIdRouteImport } from './routes/admin/user.$userId'
import { Route as AuthenticatedTaskSlotRouteImport } from './routes/_authenticated/task.$slot'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CardUidRoute = CardUidRouteImport.update({
  id: '/card/$uid',
  path: '/card/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnverifiedRoute = AdminUnverifiedRouteImport.update({
  id: '/unverified',
  path: '/unverified',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReverifyRoute = AdminReverifyRouteImport.update({
  id: '/reverify',
  path: '/reverify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRechargesRoute = AdminRechargesRouteImport.update({
  id: '/recharges',
  path: '/recharges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaidReportRoute = AdminPaidReportRouteImport.update({
  id: '/paid-report',
  path: '/paid-report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMiningRoute = AdminMiningRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacesRoute = AdminFacesRouteImport.update({
  id: '/faces',
  path: '/faces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBonusSettingsRoute = AdminBonusSettingsRouteImport.update({
  id: '/bonus-settings',
  path: '/bonus-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReverifyRoute = AuthenticatedReverifyRouteImport.update({
  id: '/reverify',
  path: '/reverify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeRoute = AuthenticatedRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhitelistRecheckRoute =
  ApiPublicWhitelistRecheckRouteImport.update({
    id: '/api/public/whitelist-recheck',
    path: '/api/public/whitelist-recheck',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTourAudioRoute = ApiPublicTourAudioRouteImport.update({
  id: '/api/public/tour-audio',
  path: '/api/public/tour-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHisabCardRoute = ApiPublicHisabCardRouteImport.update({
  id: '/api/public/hisab-card',
  path: '/api/public/hisab-card',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserUserIdRoute = AdminUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTaskSlotRoute = AuthenticatedTaskSlotRouteImport.update({
  id: '/task/$slot',
  path: '/task/$slot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/terms': typeof TermsRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/reverify': typeof AuthenticatedReverifyRoute
  '/send': typeof AuthenticatedSendRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bonus-settings': typeof AdminBonusSettingsRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/mining': typeof AdminMiningRoute
  '/admin/paid-report': typeof AdminPaidReportRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/card/$uid': typeof CardUidRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/hisab-card': typeof ApiPublicHisabCardRoute
  '/api/public/tour-audio': typeof ApiPublicTourAudioRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/terms': typeof TermsRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/reverify': typeof AuthenticatedReverifyRoute
  '/send': typeof AuthenticatedSendRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bonus-settings': typeof AdminBonusSettingsRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/mining': typeof AdminMiningRoute
  '/admin/paid-report': typeof AdminPaidReportRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/card/$uid': typeof CardUidRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin': typeof AdminIndexRoute
  '/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/hisab-card': typeof ApiPublicHisabCardRoute
  '/api/public/tour-audio': typeof ApiPublicTourAudioRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/terms': typeof TermsRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recharge': typeof AuthenticatedRechargeRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/reverify': typeof AuthenticatedReverifyRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/bonus-settings': typeof AdminBonusSettingsRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/mining': typeof AdminMiningRoute
  '/admin/paid-report': typeof AdminPaidReportRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/card/$uid': typeof CardUidRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/hisab-card': typeof ApiPublicHisabCardRoute
  '/api/public/tour-audio': typeof ApiPublicTourAudioRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/terms'
    | '/earnings'
    | '/home'
    | '/kyc'
    | '/offers'
    | '/profile'
    | '/recharge'
    | '/referral'
    | '/reverify'
    | '/send'
    | '/settings'
    | '/wallet'
    | '/withdraw'
    | '/admin/announcements'
    | '/admin/bonus-settings'
    | '/admin/faces'
    | '/admin/kyc'
    | '/admin/mining'
    | '/admin/paid-report'
    | '/admin/recharges'
    | '/admin/reverify'
    | '/admin/telegram'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/card/$uid'
    | '/email/unsubscribe'
    | '/admin/'
    | '/task/$slot'
    | '/admin/user/$userId'
    | '/api/public/hisab-card'
    | '/api/public/tour-audio'
    | '/api/public/whitelist-recheck'
    | '/lovable/email/suppression'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/terms'
    | '/earnings'
    | '/home'
    | '/kyc'
    | '/offers'
    | '/profile'
    | '/recharge'
    | '/referral'
    | '/reverify'
    | '/send'
    | '/settings'
    | '/wallet'
    | '/withdraw'
    | '/admin/announcements'
    | '/admin/bonus-settings'
    | '/admin/faces'
    | '/admin/kyc'
    | '/admin/mining'
    | '/admin/paid-report'
    | '/admin/recharges'
    | '/admin/reverify'
    | '/admin/telegram'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/card/$uid'
    | '/email/unsubscribe'
    | '/admin'
    | '/task/$slot'
    | '/admin/user/$userId'
    | '/api/public/hisab-card'
    | '/api/public/tour-audio'
    | '/api/public/whitelist-recheck'
    | '/lovable/email/suppression'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/terms'
    | '/_authenticated/earnings'
    | '/_authenticated/home'
    | '/_authenticated/kyc'
    | '/_authenticated/offers'
    | '/_authenticated/profile'
    | '/_authenticated/recharge'
    | '/_authenticated/referral'
    | '/_authenticated/reverify'
    | '/_authenticated/send'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/_authenticated/withdraw'
    | '/admin/announcements'
    | '/admin/bonus-settings'
    | '/admin/faces'
    | '/admin/kyc'
    | '/admin/mining'
    | '/admin/paid-report'
    | '/admin/recharges'
    | '/admin/reverify'
    | '/admin/telegram'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/card/$uid'
    | '/email/unsubscribe'
    | '/admin/'
    | '/_authenticated/task/$slot'
    | '/admin/user/$userId'
    | '/api/public/hisab-card'
    | '/api/public/tour-audio'
    | '/api/public/whitelist-recheck'
    | '/lovable/email/suppression'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  TermsRoute: typeof TermsRoute
  CardUidRoute: typeof CardUidRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicHisabCardRoute: typeof ApiPublicHisabCardRoute
  ApiPublicTourAudioRoute: typeof ApiPublicTourAudioRoute
  ApiPublicWhitelistRecheckRoute: typeof ApiPublicWhitelistRecheckRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$uid': {
      id: '/card/$uid'
      path: '/card/$uid'
      fullPath: '/card/$uid'
      preLoaderRoute: typeof CardUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unverified': {
      id: '/admin/unverified'
      path: '/unverified'
      fullPath: '/admin/unverified'
      preLoaderRoute: typeof AdminUnverifiedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reverify': {
      id: '/admin/reverify'
      path: '/reverify'
      fullPath: '/admin/reverify'
      preLoaderRoute: typeof AdminReverifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recharges': {
      id: '/admin/recharges'
      path: '/recharges'
      fullPath: '/admin/recharges'
      preLoaderRoute: typeof AdminRechargesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paid-report': {
      id: '/admin/paid-report'
      path: '/paid-report'
      fullPath: '/admin/paid-report'
      preLoaderRoute: typeof AdminPaidReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mining': {
      id: '/admin/mining'
      path: '/mining'
      fullPath: '/admin/mining'
      preLoaderRoute: typeof AdminMiningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faces': {
      id: '/admin/faces'
      path: '/faces'
      fullPath: '/admin/faces'
      preLoaderRoute: typeof AdminFacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bonus-settings': {
      id: '/admin/bonus-settings'
      path: '/bonus-settings'
      fullPath: '/admin/bonus-settings'
      preLoaderRoute: typeof AdminBonusSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reverify': {
      id: '/_authenticated/reverify'
      path: '/reverify'
      fullPath: '/reverify'
      preLoaderRoute: typeof AuthenticatedReverifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge': {
      id: '/_authenticated/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof AuthenticatedRechargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whitelist-recheck': {
      id: '/api/public/whitelist-recheck'
      path: '/api/public/whitelist-recheck'
      fullPath: '/api/public/whitelist-recheck'
      preLoaderRoute: typeof ApiPublicWhitelistRecheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tour-audio': {
      id: '/api/public/tour-audio'
      path: '/api/public/tour-audio'
      fullPath: '/api/public/tour-audio'
      preLoaderRoute: typeof ApiPublicTourAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hisab-card': {
      id: '/api/public/hisab-card'
      path: '/api/public/hisab-card'
      fullPath: '/api/public/hisab-card'
      preLoaderRoute: typeof ApiPublicHisabCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/$userId': {
      id: '/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AdminUserUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/task/$slot': {
      id: '/_authenticated/task/$slot'
      path: '/task/$slot'
      fullPath: '/task/$slot'
      preLoaderRoute: typeof AuthenticatedTaskSlotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRechargeRoute: typeof AuthenticatedRechargeRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedReverifyRoute: typeof AuthenticatedReverifyRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
  AuthenticatedTaskSlotRoute: typeof AuthenticatedTaskSlotRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRechargeRoute: AuthenticatedRechargeRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedReverifyRoute: AuthenticatedReverifyRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
  AuthenticatedTaskSlotRoute: AuthenticatedTaskSlotRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBonusSettingsRoute: typeof AdminBonusSettingsRoute
  AdminFacesRoute: typeof AdminFacesRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminMiningRoute: typeof AdminMiningRoute
  AdminPaidReportRoute: typeof AdminPaidReportRoute
  AdminRechargesRoute: typeof AdminRechargesRoute
  AdminReverifyRoute: typeof AdminReverifyRoute
  AdminTelegramRoute: typeof AdminTelegramRoute
  AdminUnverifiedRoute: typeof AdminUnverifiedRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUserUserIdRoute: typeof AdminUserUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBonusSettingsRoute: AdminBonusSettingsRoute,
  AdminFacesRoute: AdminFacesRoute,
  AdminKycRoute: AdminKycRoute,
  AdminMiningRoute: AdminMiningRoute,
  AdminPaidReportRoute: AdminPaidReportRoute,
  AdminRechargesRoute: AdminRechargesRoute,
  AdminReverifyRoute: AdminReverifyRoute,
  AdminTelegramRoute: AdminTelegramRoute,
  AdminUnverifiedRoute: AdminUnverifiedRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUserUserIdRoute: AdminUserUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  TermsRoute: TermsRoute,
  CardUidRoute: CardUidRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicHisabCardRoute: ApiPublicHisabCardRoute,
  ApiPublicTourAudioRoute: ApiPublicTourAudioRoute,
  ApiPublicWhitelistRecheckRoute: ApiPublicWhitelistRecheckRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
